# Generated by Django 2.1 on 2018-11-11 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_media_thumbnail'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='preferred_categories',
            field=models.ManyToManyField(to='events.EventCategory'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_sub_categories',
            field=models.ManyToManyField(to='events.EventSubCategory'),
        ),
    ]
