# Generated by Django 2.1 on 2018-11-11 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20181111_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=50)),
                ('os', models.CharField(max_length=20, null=True)),
                ('os_version', models.CharField(max_length=20, null=True)),
                ('timezone', models.CharField(max_length=50, null=True)),
                ('is_tablet', models.NullBooleanField()),
                ('push_token', models.CharField(max_length=256, unique=True)),
                ('last_login', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserProfile')),
            ],
        ),
    ]
