# Generated by Django 2.1 on 2018-11-11 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userdevice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdevice',
            name='is_tablet',
        ),
        migrations.AddField(
            model_name='userdevice',
            name='model',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
