# Generated by Django 2.1 on 2018-11-26 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20181120_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userswipeaction',
            name='action',
            field=models.IntegerField(choices=[(1, 'LEFT'), (0, 'UP'), (3, 'RIGHT'), (2, 'DOWN')], default=1),
        ),
    ]
