# Generated by Django 2.1 on 2019-01-22 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20190122_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='fb_profile_image_normal',
            field=models.ImageField(editable=False, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='userdata',
            name='fb_profile_image_small',
            field=models.ImageField(editable=False, null=True, upload_to=''),
        ),
    ]
