# Generated by Django 2.1 on 2019-01-22 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20190122_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='fb_profile_image_large',
            field=models.ImageField(editable=False, null=True, upload_to=''),
        ),
    ]
