# Generated by Django 2.1 on 2019-03-03 12:45

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20190228_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRelations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.IntegerField(choices=[(0, 'Friend')], default=0)),
                ('state', models.IntegerField(choices=[(0, 'Pending'), (1, 'Connected')], default=0)),
                ('meta_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, editable=False, null=True)),
                ('related_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_relations_related', to='users.UserProfile')),
                ('relating_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_relations_relating', to='users.UserProfile')),
            ],
        ),
    ]
