# Generated by Django 2.1 on 2019-03-05 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_userrelations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user_data',
        ),
        migrations.AddField(
            model_name='userdata',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.UserProfile'),
        ),
    ]
