# Generated by Django 2.1 on 2019-03-29 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20190305_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='userswipeaction',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=0, editable=False, max_digits=9),
        ),
        migrations.AddField(
            model_name='userswipeaction',
            name='lng',
            field=models.DecimalField(decimal_places=6, default=0, editable=False, max_digits=9),
        ),
    ]
