# Generated by Django 2.1 on 2019-04-01 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20190329_0945'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'Add Event'), (1, 'Feedback'), (2, 'Contact')], default=1)),
                ('text', models.CharField(blank=True, max_length=1000)),
                ('lng', models.DecimalField(decimal_places=6, default=0, editable=False, max_digits=9)),
                ('lat', models.DecimalField(decimal_places=6, default=0, editable=False, max_digits=9)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.UserProfile')),
            ],
        ),
    ]
