# Generated by Django 2.1.8 on 2019-04-03 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_usermessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessage',
            name='text',
            field=models.CharField(blank=True, editable=False, max_length=1000),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='type',
            field=models.IntegerField(choices=[(0, 'Add Event'), (1, 'Feedback'), (2, 'Contact')], default=1, editable=False),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='user',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.UserProfile'),
        ),
    ]
