# Generated by Django 2.1 on 2018-08-29 16:32

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import events.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(blank=True, upload_to=events.models.Artist.artist_media_path)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, db_index=True, max_length=200)),
                ('short_description', models.CharField(blank=True, max_length=200)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('price', models.IntegerField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('promotion', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to=events.models.EventCategory.event_category_media_path)),
            ],
        ),
        migrations.CreateModel(
            name='EventSubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to=events.models.EventSubCategory.event_sub_category_media_path)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.EventCategory')),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('IMG', 'Image'), ('AUD', 'Audio'), ('VID', 'Video')], default='IMG', max_length=3)),
                ('source', models.CharField(choices=[('SRC_EVENT', 'Event'), ('SRC_ARTIST', 'Artist')], default='SRC_EVENT', max_length=10)),
                ('link', models.URLField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='UserSwipeAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('LEFT', 'Left'), ('TOP', 'Top'), ('RIGHT', 'Right'), ('BOTTOM', 'Bottom')], default='LEFT', max_length=6)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.Event')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('street_address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('link', models.URLField(blank=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.EventCategory'),
        ),
        migrations.AddField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.UserProfile'),
        ),
        migrations.AddField(
            model_name='event',
            name='media',
            field=models.ManyToManyField(blank=True, to='events.Media'),
        ),
        migrations.AddField(
            model_name='event',
            name='sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.EventSubCategory'),
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.Venue'),
        ),
        migrations.AddField(
            model_name='artist',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.EventCategory'),
        ),
        migrations.AddField(
            model_name='artist',
            name='media',
            field=models.ManyToManyField(blank=True, to='events.Media'),
        ),
    ]
