# Generated by Django 2.1 on 2018-08-16 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20180816_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='media',
            field=models.ManyToManyField(blank=True, to='events.Media'),
        ),
    ]
