# Generated by Django 2.1 on 2018-08-31 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20180831_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
