# Generated by Django 2.1 on 2018-08-21 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20180816_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='artist',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='media',
            field=models.ManyToManyField(blank=True, to='events.Media'),
        ),
        migrations.AlterField(
            model_name='media',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
