# Generated by Django 2.1 on 2018-11-20 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_media_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userswipeaction',
            name='event',
        ),
        migrations.RemoveField(
            model_name='userswipeaction',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserSwipeAction',
        ),
    ]
