# Generated by Django 2.1 on 2018-12-23 12:02

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20181223_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, upload_to=events.models.Event.events_media_path),
        ),
    ]
