# Generated by Django 2.1 on 2018-12-30 13:31

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_event_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50)),
                ('icon', models.ImageField(blank=True, null=True, upload_to=events.models.Audience.audiences_media_path)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='audiences',
            field=models.ManyToManyField(blank=True, to='events.Audience'),
        ),
    ]
