# Generated by Django 2.1 on 2018-12-30 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20181230_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcategory',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='eventsubcategory',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
