# Generated by Django 2.1 on 2018-12-30 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20181230_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='audience',
            name='title_heb',
            field=models.CharField(db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='title_heb',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='audiences',
            field=models.ManyToManyField(to='events.Audience'),
        ),
        migrations.RemoveField(
            model_name='event',
            name='category',
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.ManyToManyField(to='events.EventCategory'),
        ),
    ]
