# Generated by Django 2.1 on 2018-12-30 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_auto_20181230_1559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='category',
            new_name='categories',
        ),
    ]
