# Generated by Django 2.1 on 2018-12-31 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20181231_1219'),
        ('events', '0012_auto_20181230_1601'),
    ]

    operations = [
    ]
