# Generated by Django 2.1 on 2019-01-07 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_auto_20181230_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description_heb',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='event',
            name='short_description_heb',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='event',
            name='title_heb',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
    ]
