# Generated by Django 2.1 on 2019-01-07 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_auto_20190107_0724'),
        ('events', '0013_merge_20181231_1246'),
    ]

    operations = [
    ]
