# Generated by Django 2.1 on 2019-01-08 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_merge_20190107_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='city_heb',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='name_heb',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='street_address_heb',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='title_heb',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
    ]
