# Generated by Django 2.1 on 2019-03-07 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_event_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcategory',
            name='icon_name',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
