# Generated by Django 2.1 on 2019-03-06 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_event_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='playback_end',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='playback_start',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='youtube_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='type',
            field=models.CharField(choices=[('IMG', 'Image'), ('AUD', 'Audio'), ('VID', 'Video'), ('YT', 'Youtube')], default='IMG', max_length=3),
        ),
    ]
