# Generated by Django 2.1 on 2019-03-30 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_eventcategory_icon_name'),
        ('events', '0020_auto_20190306_1300'),
    ]

    operations = [
    ]
