# Generated by Django 2.1 on 2019-03-31 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_eventcategory_icon_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='tickets_link',
            field=models.URLField(blank=True),
        ),
    ]
