# Generated by Django 2.1 on 2019-04-02 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_event_tickets_link'),
        ('events', '0021_merge_20190330_2000'),
    ]

    operations = [
    ]
