# Generated by Django 2.1.8 on 2019-04-05 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_merge_20190402_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='first_name_heb',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='artist',
            name='last_name_heb',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
