# Generated by Django 2.1.8 on 2019-04-07 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_auto_20190405_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
