# Generated by Django 2.1.8 on 2019-04-08 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0024_auto_20190407_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='image_credits',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
