# Generated by Django 2.1.8 on 2019-05-02 10:58

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0025_artist_image_credits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='latitude',
        ),
        migrations.AddField(
            model_name='venue',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326, verbose_name='Location'),
        ),
    ]
