# Generated by Django 2.1.8 on 2019-05-06 05:08

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0026_auto_20190502_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Location'),
        ),
    ]
