# Generated by Django 2.1.8 on 2019-05-16 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0027_auto_20190506_0808'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='tag',
            field=models.CharField(default='please_set_tag', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='media',
            name='source',
            field=models.CharField(choices=[('SRC_EVENT', 'Event'), ('SRC_ARTIST', 'Artist')], default='SRC_ARTIST', max_length=10),
        ),
    ]
