# Generated by Django 2.1.8 on 2019-05-19 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0028_auto_20190516_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='longitude',
        ),
    ]
