# Generated by Django 2.1.8 on 2019-05-19 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0029_remove_venue_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='link',
            field=models.URLField(blank=True, max_length=400),
        ),
    ]
