# Generated by Django 2.1.8 on 2019-05-20 08:03

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0032_auto_20190520_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=events.models.Event.events_media_path),
        ),
    ]
