# Generated by Django 2.1.8 on 2019-05-24 08:39

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0033_auto_20190520_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='additional_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
