# Generated by Django 2.1.8 on 2019-05-30 13:52

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0034_event_additional_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='additional_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
