# Generated by Django 2.1.8 on 2019-05-30 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0035_venue_additional_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.Artist'),
        ),
        migrations.AlterField(
            model_name='event',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
